version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
    volumes:
      - vw-data:/data
    deploy:
      labels:
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.$webappname$.entrypoints: https
        traefik.http.routers.$webappname$-http.entrypoints: http
        traefik.http.routers.$webappname$.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$-http.middlewares: https-redirect
        traefik.http.routers.$webappname$-http.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$.service: $webappname$
        traefik.http.routers.$webappname$.tls: 'true'
        traefik.http.routers.$webappname$.tls.certresolver: le
        traefik.http.services.$webappname$.loadbalancer.server.port: 80

volumes:
  vw-data: null
networks:
  default:
    external:
      name: traefik-public