version: "3"
services:
  code-server:
    image: linuxserver/code-server:4.4.0
    container_name: code-server
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Specify a timezone to use EG Europe/London
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
    volumes:
      - code-server_data:/config # Contains all relevant configuration files.
    ports:
      - :8443

    deploy:
      labels:
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.$webappname$.entrypoints: https
        traefik.http.routers.$webappname$-http.entrypoints: http
        traefik.http.routers.$webappname$.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$-http.middlewares: https-redirect
        traefik.http.routers.$webappname$-http.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$.service: $webappname$
        traefik.http.routers.$webappname$.tls: 'true'
        traefik.http.routers.$webappname$.tls.certresolver: le
        traefik.http.services.$webappname$.loadbalancer.server.port: 8443
volumes:
  code-server_data: null
networks:
  default:
    external:
      name: traefik-public