version: '3'
services:
  database:
    image: postgres:13.4-alpine
    networks:
      - default
    environment:
      # Ersetzen Sie Benutzername und Kennwort durch individuelle Zugangsdaten. Sie sind nur für die Datenbank, nicht das Webinterface.
      - POSTGRES_USER=$webappname$
      - POSTGRES_PASSWORD=magdus-wazwiz-5pYjsy
      - POSTGRES_DB=hedgedoc
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  app:
    # Prüfen Sie unter https://hedgedoc.org/latest-release welche Version aktuell ist und ersetzen Sie ggf. die Versionsnummer
    image: quay.io/hedgedoc/hedgedoc:1.9.3
    networks:
      - traefik-public
      - default
    environment:
      # Grundeinstellungen
      ## Zeitzone
      - TZ=Europe/Berlin
      
      ## Hier die oben eingestellten Datenbank-Zugangsdaten eintragen
      - CMD_DB_URL=postgres://$webappname$:magdus-wazwiz-5pYjsy@database:5432/hedgedoc
      
      ## Tragen Sie hier die Domain ein, über die Sie auf das HedgeDoc zugreifen (auch, wenn die Domain über einen HTTP-Reverse-Proxy genutzt wird)
      - CMD_DOMAIN=$webappname$.webapp-store.de
      
      ## Sorgt dafür, dass abweichende Ports (bspw. 3000) an die URL angehängt werden. Nicht notwendig bei 80/443.
      - CMD_URL_ADDPORT=true
      
      ## Muss gesetzt werden, wenn TLS zum Einsatz kommt -- egal ob lokal oder per Reverse-Proxy.
      - CMD_PROTOCOL_USESSL=true
      
      ## Port, auf dem HedgeDoc seinen Webserver startet
      - CMD_PORT=443
      
      #Login
      ## Erlaubt/Verbietet Login per E-Mail
      - CMD_EMAIL=true
      
      ## Erlaubt/Verbietet Registrierung per E-Mail
      - CMD_ALLOW_EMAIL_REGISTER=true
      ## Weitere Login-Methoden finden Sie unter https://docs.hedgedoc.org/configuration/#login-methods
      
      # Zugangsrechte      
      ## Erlaubt/Verbietet unregistrierten Nutzern Notizen zu erstellen
      - CMD_ALLOW_ANYMOUS=true
      
      ## Erlaubt/Verbietet unregistrierten Nutzern Notizen zu bearbeiten
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      
      ## Erlaubt/Verbietet statt zufälligen URLs frei wählbare, bspw. https://hedgedoc.example.de/quartalszahlen
      - CMD_ALLOW_FREEURL=true
      
      ## Setzt das voreingestellte Rechteprofil, wenn eine neue Notiz erstellt wird: freely, editable, limited, locked, protected, private
      - CMD_DEFAULT_PERMISSION=freely

    volumes:
      - "app:/hedgedoc/public/uploads"
    deploy: 
      labels: 
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.$webappname$.entrypoints: https
        traefik.http.routers.$webappname$-http.entrypoints: http
        traefik.http.routers.$webappname$-http.middlewares: https-redirect
        traefik.http.routers.$webappname$.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$.service: $webappname$
        traefik.http.routers.$webappname$.tls: 'true'
        traefik.http.routers.$webappname$.tls.certresolver: le
        traefik.http.services.$webappname$.loadbalancer.server.port: 443
    restart: always
    depends_on:
      - database
 
volumes:
  dbdata:
  app:

networks:
  traefik-public:
    external: true