version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    networks:
      - traefik-public
      - default
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: $webappname$64816kgdjn
      REDMINE_SECRET_KEY_BASE: $webappname$
    deploy:
      labels:
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.$webappname$.entrypoints: https
        traefik.http.routers.$webappname$-http.entrypoints: http
        traefik.http.routers.$webappname$.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$-http.middlewares: https-redirect
        traefik.http.routers.$webappname$-http.rule: Host(`$webappname$.webapp-store.de`)
        traefik.http.routers.$webappname$.service: $webappname$
        traefik.http.routers.$webappname$.tls: 'true'
        traefik.http.routers.$webappname$.tls.certresolver: le
        traefik.http.services.$webappname$.loadbalancer.server.port: 3000

  db:
    image: mysql:5.7
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: $webappname$64816kgdjn
      MYSQL_DATABASE: redmine

networks:
  traefik-public:
    external: true
